# -*- coding: utf-8 -*-
"""Linear_Algebra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IkEJmd8I8fpZ8i9GPUIOA7c5tI2li3nA

# **Linear Algebra**
### **A. Vectors**
  
A student can be represented as:

math marks = 86

physics marks = 82

chemistry marks = 88

         v=[86,82,88]
vector = collection of features
"""

#Scalars
x = 5
y = 10.5
print(x)
print(y)

#Vector
import numpy as np
v = np.array([25, 30, 80])
print(v)
print(v.shape)
print(v.ndim)

#Matrix
# Rows = students
# Columns = subjects
import numpy as np
students = np.array([
    [80, 50, 80],
    [80, 70, 90],
    [50, 60, 30]]
)
print(students)
print(students.shape)
print(students.ndim)  #used for check dimensions

